# Generated by Django 4.0.3 on 2022-03-10 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiteams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apimatches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('updated', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('ipl_winner', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('defaulted', 'Defaulted'), ('won', 'Won'), ('lost', 'Lost'), ('no-result', 'No Result')], default='placed', max_length=20)),
                ('result', models.FloatField(default=0)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apimatches.match')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiteams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'match', 'team')},
            },
        ),
    ]
