# Generated by Django 4.0.3 on 2022-03-10 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiteams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('type', models.CharField(choices=[('league', 'League'), ('knockout', 'KnockOut')], default='league', max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('abandoned', 'Abandoned')], default='completed', max_length=20)),
                ('win_type', models.CharField(blank=True, choices=[('runs', 'Runs'), ('wickets', 'Wickets'), ('super', 'Super Over')], max_length=10, null=True)),
                ('win_margin', models.PositiveIntegerField(blank=True, null=True)),
                ('bat_first', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bat_first', to='apiteams.team')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeHistory', to='apiteams.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayHistory', to='apiteams.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winnerHistory', to='apiteams.team')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('all', 'All'), ('home', 'Home'), ('away', 'Away'), ('batfirst', 'Bat First'), ('knockout', 'Knockout'), ('last10', 'Last10')], default='all', max_length=20)),
                ('played', models.PositiveSmallIntegerField(default=0)),
                ('won', models.PositiveSmallIntegerField(default=0)),
                ('probability', models.PositiveSmallIntegerField(default=0)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeStats', to='apiteams.team')),
                ('team2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awayStats', to='apiteams.team')),
            ],
            options={
                'verbose_name_plural': 'TeamStats',
                'unique_together': {('team1', 'team2', 'type')},
            },
        ),
    ]
