"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from datetime import timedelta
from os import getenv
from pathlib import Path

from dotenv import load_dotenv

# Pointing to IPL2022 folder
BASE_DIR = Path(__file__).resolve().parent.parent.parent
load_dotenv(BASE_DIR / '.env')


SECRET_KEY = getenv("SECRET_KEY")
DEBUG = getenv("DEBUG") == "True"
PRODUCTION = getenv("PRODUCTION") == "True"
ALLOWED_HOSTS = []

# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',

]

LOCAL_APPS = [
    'core.apps.CoreConfig',
    'apiusers.apps.ApiusersConfig',
    'apiteams.apps.ApiteamsConfig',
    'apimatches.apps.ApimatchesConfig',
    'apipredictions.apps.ApipredictionsConfig',
    'apistats.apps.ApistatsConfig',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
DATABASES = {}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/


STATIC_URL = '/assets/static/'
MEDIA_URL = '/assets/media/'
STATIC_ROOT = BASE_DIR / "assets" / "static"
MEDIA_ROOT = BASE_DIR / "assets" / "media"
STATICFILES_DIRS = [BASE_DIR / 'static']

# User Model
AUTH_USER_MODEL = 'apiusers.UserAccount'

# Default primary key field type

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Rest Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    )
}

# JWT Settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=10),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
}
JWT_COOKIE_NAME = getenv("JWT_COOKIE_NAME")
JWT_COOKIE_SAMESITE = getenv("JWT_COOKIE_SAMESITE")
JWT_COOKIE_SECURE = getenv("JWT_COOKIE_SECURE") == "True"

# Cors Configuration
CORS_ALLOW_CREDENTIALS = True


# Local Apps Configuration
TEAM_CHOICES = [
    ('CSK', 'Chennai Super Kings'),
    ('DC', 'Delhi Capitals'),
    ('KKR', 'Kolkata Knight Riders'),
    ('MI', 'Mumbai Indians'),
    ('SRH', 'Sunrisers Hyderabad'),
    ('RCB', 'Royal Challengers Bangalore'),
    ('RR', 'Rajasthan Royals'),
    ('PBKS', 'Punjab Kings'),
    ('KOC', 'Kochi Tuskers'),
    ('RPSG', 'Rising Pune Supergiants'),
    ('GL', 'Gujarat Lions'),
    ('GT', 'Gujarat Titans'),
    ('LSG', 'Lucknow Super Giants'),
]

MATCH_STATUS = [
    ("scheduled", "Scheduled"),
    ("completed", "Completed"),
    ("abandoned", "Abandoned"),
]

MATCH_TYPES = [
    ("league", "League"),
    ("qualifier1", "Qualifier-1"),
    ("qualifier2", "Qualifier-2"),
    ("eliminator", "Eliminator"),
    ("final", "Final"),
]

WIN_TYPES = [
    ('runs', 'Runs'),
    ('wickets', 'Wickets'),
    ('super', 'Super Over'),
]

STATS_MATCH_TYPES = [
    ("league", "League"),
    ("knockout", "KnockOut"),
]

PREDICTION_STATUS_TYPES = [
    ("placed", "Placed"),
    ("defaulted", "Defaulted"),
    ("won", "Won"),
    ("lost", "Lost"),
    ("no-result", "No Result"),
]

STATS_TYPES = [
    ("all", "All"),
    ("home", "Home"),
    ("away", "Away"),
    ("batfirst", "Bat First"),
    ("knockout", "Knockout"),
    ("last10", "Last10"),
]
