# Generated by Django 4.0.3 on 2022-03-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimatches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team1_overs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2_overs',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
