# Generated by Django 4.0.3 on 2022-03-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimatches', '0002_alter_match_team1_overs_alter_match_team2_overs'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='double',
            field=models.BooleanField(default=False),
        ),
    ]
