# Generated by Django 4.0.3 on 2022-03-10 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiteams', '0001_initial'),
        ('apiusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipl_admin', models.BooleanField(default=False, verbose_name='IPL Admin')),
                ('played', models.PositiveSmallIntegerField(default=0)),
                ('won', models.PositiveSmallIntegerField(default=0)),
                ('lost', models.PositiveSmallIntegerField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('ipl_winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiteams.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-amount', '-won', 'lost'),
            },
        ),
    ]
