# Generated by Django 4.0.3 on 2022-03-10 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('short_name', models.CharField(choices=[('CSK', 'Chennai Super Kings'), ('DC', 'Delhi Capitals'), ('KKR', 'Kolkata Knight Riders'), ('MI', 'Mumbai Indians'), ('SRH', 'Sunrisers Hyderabad'), ('RCB', 'Royal Challengers Bangalore'), ('RR', 'Rajasthan Royals'), ('PBKS', 'Punjab Kings'), ('KOC', 'Kochi Tuskers'), ('RPSG', 'Rising Pune Supergiants'), ('GL', 'Gujarat Lions'), ('GT', 'Gujarat Titans'), ('LSG', 'Lucknow Super Giants')], max_length=4, primary_key=True, serialize=False)),
                ('long_name', models.CharField(blank=True, max_length=30, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('short_name',),
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.PositiveSmallIntegerField(default=0)),
                ('won', models.PositiveSmallIntegerField(default=0)),
                ('lost', models.PositiveSmallIntegerField(default=0)),
                ('draw', models.PositiveSmallIntegerField(default=0)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('runs_scored', models.PositiveSmallIntegerField(default=0)),
                ('runs_given', models.PositiveSmallIntegerField(default=0)),
                ('balls_faced', models.PositiveSmallIntegerField(default=0)),
                ('balls_bowled', models.PositiveSmallIntegerField(default=0)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apiteams.team')),
            ],
        ),
    ]
